### ISSUE TITLE
[GDI - ckan - SPIKE] How do we load URI labels into database? 

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-ckan-docker#21]
## What
How do we load URI labels into database? Test it with languages.

## Why

So whenever one is editing datasets in CKAN or a harvester is loading a new dataset, we have language labels associate to URI's.

## Tasks
- Create datastore database in Postgres and configure CKAN properly (e.g. https://github.com/ckan/ckan-docker)
- Load [languages.csv](https://github.com/GenomicDataInfrastructure/gdi-userportal-ckan-docker/files/13780768/languages.csv) into datastore

## Acceptance criteria
- Is datastore configured in this project?
- Is loading languages csv documented in gdi-userportal-docs?
- Is the datastore configuration documented in gdi-userportal-docs?

**Comment by hcvdwerf** [comment]
Not yet experience from here with this topic

**Comment by hcvdwerf** [comment]
We just saw that not everything is moved: 
https://github.com/CivityNL/ckanext-civity/blob/main/ckanext/civity/resources/vocabularies/donl_language.json

Options are
- Copy to FDP extension 
- Copy to GDI extension 
-Seperate extension for languages

**Comment by brunopacheco1** [comment]
Good spot.

As this is related to GDI schema, it should go with `ckanext-gdi-useprortal`. I believe for know it should not be a problem having the labels defined like that. But the harvesting is not dependent on the software lifecycle, so should not be the labels definition. 

I mean, labels should be also harvested, or at least persisted in the database, where we could patch time to time new entries/updates more easily.
