### ISSUE TITLE
[GDI - ckan - SPIKE] How does FAIR Data Points harvester behave with a source that contains Distribution?

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-ckan-docker#23]
## What

Test FAIR Data Points harvester with a source that contains Distribution.

## Why

`https://fair.healthinformationportal.eu/` does not contain distributions, so we don't know how the harvester behaves.

## Acceptance Criteria
- Is the output of the test documented in gdi-useportal-docs?
- Are new stories created to fix any problem, if anything is needed? 

## Tasks
- Find another FAIR Data Point source and test harvesting.
- Document findings on https://genomicdatainfrastructure.github.io/gdi-userportal-docs/docs/ckan/harvester/harvesting-fair-data-points/
- Create new stor(y|ies) to plan this change, if needed.

**Comment by hcvdwerf** [comment]
This faidatapoint contains distributions. For development/testing purposes you can use it:  https://health-ri.sandbox.semlab-leiden.nl

**Comment by brunopacheco1** [comment]
This has been tested and it is working as expected.

<img width="1718" alt="image" src="https://github.com/GenomicDataInfrastructure/gdi-userportal-ckan-docker/assets/4491850/ae6baa8b-cfe5-43bd-9f9d-bc6f4554735e">
